### ISSUE TITLE
I hope to see the name of the planet and the weather

### ISSUE THREAD

**Issue by apeng0907** [stormytuna/RouteRandom#10]
I want to automatically land on a random planet after entering random again, but the screen will display information about the planet. However, the content of the last configuration file can only be hidden. Please divide it into two parts: whether to automatically land and whether to hide the planet

**Comment by stormytuna** [comment]
Closing as, if I understand you properly, I don't plan on making it possible to automatically land after randomly choosing a moon. Please reopen with more clarification if that's not the case

**Comment by apeng0907** [comment]
#Hides the planet you get randomly routed to, both in the terminal response and at the helm. NOTE: This will ALWAYS hide the orbited planet (even when selected manually) and will skip the confirmation screen

I want this setting to be divided into two parts, one is whether to hide planet and weather information, and the other is whether to automatically land.This is important for me and my friends because we want to land automatically after a random planet, but we can see information about the planet.
