### ISSUE TITLE
Reverse the commands

### ISSUE THREAD

**Issue by DeathWrench** [stormytuna/RouteRandom#11]
Since it's a mouthful to type out randomfilterweather it would be better if it was the other way around. 
randomfilterweather => random
random => randomignoreconfig 
This is how I've set it up for myself. 
![image](https://github.com/stormytuna/RouteRandom/assets/45341450/8ccab1a4-a205-45f4-a4ec-7c2b78d22030)

**Comment by stormytuna** [comment]
Closing as I won't be doing this
