### ISSUE TITLE
[Request] Automatic Routing once you reach Orbit

### ISSUE THREAD

**Issue by Pockett-Dev** [stormytuna/RouteRandom#12]
Hey there,

I was wondering if it would be possible for you to add a configuration that would automatically route to the next moon once you reach orbit after leaving the Company facility and other moons? Other mods have this functionality, HOWEVER, they implement it in a bad way - they randomly choose a moon **once you pull the lever** which I've noticed that this breaks modded moons. However, I believe that if you randomly route before pulling the lever (aka, when the ship reaches orbit), in theory, it should work just fine.

Maybe someone sort of configuration option to stop people from manually selecting moons and spamming the route random command might be cool too? :D 

Hopefully I explained my ideas well...if you have any questions about what I'm talking about, let me know! :) If you have any way I can donate to you that'd be very cool too - cheers!

**Comment by stormytuna** [comment]
While this is a great idea I think it would be better suited for another mod. The point of this mod is having the option to ignore the randomly chosen moon, it would be too much effort to remove that option entirely just for the sake of a config that's turned off by default and 90% of players won't even know exists

Closing as not planned for this mod
