### ISSUE TITLE
Can not confirm for randomly chosen costly moon

### ISSUE THREAD

**Issue by NeuTraLZero** [stormytuna/RouteRandom#2]
This is even when RemoveCostOfCostlyPlanets is set to true

**Comment by nickjuricic** [comment]
I also have the same issue you described.

**Comment by Seathroath** [comment]
i am also having this issue. The only way to by-pass it was to enable skip confirmation option.

**Comment by Ryu776** [comment]
none of the configs seems to be working for me aside from the skip confirm

**Comment by stormytuna** [comment]
Could you provide some more details, what exactly is the issue? Can you give any reproduction steps - what configs are enabled, what command do you type, what happens vs what you expect, etc

**Comment by darkanx** [comment]
ALLOWED WEATHERS
all default
COSTLY PLANETS
AllowCostlyPlanets=true
RemoveCostOfCostyPlanets=true
GENERAL
SkipConfirmation=false
DifferentPlanetEachTime=false
HidePlanet=false

When you type in Random, it asks you to "confirm or deny", you are unable to hit return after typing in any confirmation. You can type a response, it just will not accept pressing enter.

Setting SkipConfirmation to true skips that step, thus working around the issue.

**Comment by stormytuna** [comment]
Closing as fixed in [9b4b6c6](https://github.com/stormytuna/RouteRandom/commit/9b4b6c62fcfc5f6a3bd64080d632ecce70fdfdbb)
