### ISSUE TITLE
Different weather online

### ISSUE THREAD

**Issue by Yukine19** [stormytuna/RouteRandom#3]
My friends and I all have the RouteRandom installed but when we route the ship to a random map, I usually don't see any weather conditions, but my friends will see it. One time we chose random and we landed on Rend but apparently it was flooded for them and it was normal for me so I didn't see any water. I was able to walk through with ease. Another time we landed on Titan and it was stormy for them but normal for me. They said that I would keep getting electrocuted and wouldn't die. 

Is there a way to fix this?

**Comment by stormytuna** [comment]
That's a very common issue if people are not using the same mods, the random generators this mod uses do not affect the existing map generators that are synced between clients

Closing as likely not this mods issue, please reopen with more information if you can repro with just this mod enabled on all sides
