### ISSUE TITLE
Route Random with Mod Moons

### ISSUE THREAD

**Issue by SlonzyJr** [stormytuna/RouteRandom#6]
can you make the mod work with moded moons?

**Comment by darkanx** [comment]
Indeed it does not. I was going to request this issue fixed as well, but found another mod that works https://thunderstore.io/c/lethal-company/p/Beauver/ExtraTerminalCommands/

**Comment by stormytuna** [comment]
Closing as completed in ddbc214053fa4b24b2a36ab8839fd30eb1862654
