### ISSUE TITLE
Route command missing terminalOptions variable (?)

### ISSUE THREAD

**Issue by Index154** [stormytuna/RouteRandom#9]
I've been having game breaking issues when using this mod together with the mod LethalQuantities. After informing the creator of LethalQuantities about the specific errors I was getting they looked into it on their side and told me this:

> RouteRandom adds multiple CompatibleNouns to the route command's list of CompatibleNouns, but their terminalOptions variable is null, which is unexpected since all route CompatibleNouns are expected to have a valid confirm CompatibleNoun. I've added in more checks on my end to test the CompatibleNouns more thoroughly next update, but this is an issue with how RouteRandom implements their random commands.

The issue has already been "fixed" now through the efforts of the LethalQuantities creator implementing more checks for null variables. I just thought I'd let you know about this to maybe prevent incompatibilities with other mods.

**Comment by stormytuna** [comment]
Closing as fixed in 41d779950c35e2f1e6b2c9ac18fa3f257975b40e
